repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: \.psd1$
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: check-xml
  - id: check-added-large-files

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.27.0
  hooks:
  - id: gitleaks

- repo: https://github.com/editorconfig-checker/editorconfig-checker
  rev: v3.3.0
  hooks:
  - id: editorconfig-checker
