USERNAME = jasperes
DEBIAN_NAME = bookworm

SHELL_NAME = zsh
SHELL_BIN = /bin/zsh
SHELL_RC = ~/.zshrc

SCRIPTS = ./scripts
RESOURCES = ./resources
TEMP = ./temp

RC_FOLDER = ${HOME}/Sources/jasperes/debian/dotfiles
APPIMAGE_FOLDER = ${HOME}/.local/appimage

#NVIDIA_INSTALLER = ./nvidia/NVIDIA-Linux-x86_64-550.144.03.run

SWAP_FILE = /swapfile
SWAP_SIZE = 16384
