[tools]
"asdf:usage" = "latest"

node = "22"
"npm:yarn" = "latest"

python = "3.13"
pipx = "latest"
"pipx:ansible" = "latest"

"aqua:terraform" = "latest"
"aqua:kubectl" = "latest"
"aqua:nerdctl" = "latest"
"asdf:powershell-core" = "latest"
"asdf:dotnet-core" = "8"

[settings]
experimental = true
