[tools]
azure = "2"
bun = "latest"
dotnet = "8"
go = "latest"
helm = "latest"
java = "21"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
node = "22"
"npm:yarn" = "latest"
"pipx:ansible" = "latest"
"pipx:poethepoet" = "latest"
"pipx:poetry" = "latest"
podman = "latest"
powershell = "7"
python = "3.13"
terraform = "latest"
usage = "latest"

[settings]
experimental = true
pipx_uvx = true
fetch_remote_versions_timeout = "30s"
